### ISSUE TITLE
Add support for the "fields" query parameter

### ISSUE THREAD

**Issue by cmeeren** [scott-mcdonald/JsonApiFramework#52]
I have to support the `fields[]` query parameter to control which fields/relationships are included in the response and which aren't. However, I can't seem to figure out how to make this work. I can't use `NullValueHandling.Ignore` and set the excluded values to `null`, because in that case, values that should be included but have a real `null` value aren't included.

For example, consider the case of an `Order` resource with a property `customer-note`. If the customer note is not set, it should be `null` and included in the response, but with `NullValueHandling.Ignore`, it's not included in the result at all. And if I don't use `NullValueHandling.Ignore`, all excluded fields (as per the `fields[]` query parameter) are included in the response with value `null`.

Is there a solution to this in JsonApiFramework that I haven't come across? If not, do you have another suggestion for how to achieve this, or could it perhaps be implemented?

**Comment by scott-mcdonald** [comment]
I do not have direct support for this but would be an excellent feature enhancement that is straightforward to implement. Note that **fields** per the json:api specification includes both _attributes_ and _relationships_. We will be retooling our API where I work and there will be a need for this feature to implement "sparse fieldsets" as documented in the json::api specification. I am going to add this in the next release...

**Comment by scott-mcdonald** [comment]
After thinking about this feature I have come to the conclusion the best way to support this feature for developers (including myself) using JsonApiFramework is to have JsonApiFramework parse and handle the query parameter "fields" per the json:api specification because basically the entire current request URI (which includes any query parameters) is already being passed in the `NewDocument` method of a server-side DocumentContext object. Originally I was toying with the idea of having some kind of "Fields" methods on the builder interface but this is actually cleaner and more useful/helpful in my opinion. Also this applies to #48 for the "include" query parameter. This seems obvious now but it did take me some time to arrive at this implementation detail and just wanted to document this decision for the record...

**Comment by cmeeren** [comment]
Could you also then surface a simple way to check programatically whether a field is included or not? If an expensive field is excluded, it would be desirable to programatically determine this so it can be set to `null` or similar, instead of spending time fetching data that will be skipped on serialization anyway.

**Comment by scott-mcdonald** [comment]
@cmeeren I like your idea. Something like a new way to call `NewDocument` method, you would pass an object that is created outside/before the `NewDocument` method that takes the current request URL and "parses" what "fields" are to be included/excluded per type and what "includes" are to be included/excluded based on the current "service model". The developer can then use this to optimize what "fields" and "related resources" to actually "work" on. I used a lot of "air quotes" but in general I like this concept - would be useful IMHO...
